apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  namespace: release-lab
  labels:
    app: release-app
    strategy: canary
    release: canary
    version: v2
    owner: devops-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-app
      strategy: canary
      release: canary
  template:
    metadata:
      labels:
        app: release-app
        strategy: canary
        release: canary
        version: v2
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: release-app
          image: release-lab:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: VERSION
              value: "v2"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "246Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
        