apiVersion: v1
kind: Service
metadata:
  name: canary-service
  namespace: release-lab
spec:
  selector:
    app: release-app
    strategy: canary
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: NodePort