apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: inventory-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Krish0257/k8s-projects.git
    targetRevision: main
    path: inventory

  destination:
    server: https://kubernetes.default.svc
    namespace: release-lab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true